# See https://github.com/JuliaLang/Example.jl/blob/master/.travis.yml

language: julia

os:
- linux

julia:
- 1.0   # LTS release
- 1.4   # Current stable release
- nightly

notifications:
  email: false

addons:
  postgresql: "9.4"

before_script:
- createdb -U postgres test

env:
  global:
  - DOCUMENTER_DEBUG=true
  - PGHOST=/var/run/postgresql
  - PGPORT=5432
  - PGUSER=postgres
  - PGDATABASE=test

after_success:
# push coverage results
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
  - julia: nightly
  include:
  # deploy documentation
  - stage: "Documentation"
    os: linux
    julia: 1.0
    script:
    - julia --project=doc -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=doc doc/make.jl
    after_success: skip
